/*----- PROTECTED REGION ID(SnmpStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: SnmpStateMachine.cpp,v 1.1.1.1 2014-04-15 08:04:23 alessio Exp $";
//=============================================================================
//
// file :        SnmpStateMachine.cpp
//
// description : State machine file for the Snmp class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: alessio $
//
// $Revision: 1.1.1.1 $
// $Date: 2014-04-15 08:04:23 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Snmp.h>

/*----- PROTECTED REGION END -----*/	//	Snmp::SnmpStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Snmp_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Snmp::is_Get_allowed()
 *	Description : Execution allowed for Get attribute
 */
//--------------------------------------------------------
bool Snmp::is_Get_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Get command.
	/*----- PROTECTED REGION ID(Snmp::GetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Snmp::GetStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Snmp::is_Set_allowed()
 *	Description : Execution allowed for Set attribute
 */
//--------------------------------------------------------
bool Snmp::is_Set_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Set command.
	/*----- PROTECTED REGION ID(Snmp::SetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Snmp::SetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(Snmp::SnmpStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Snmp::SnmpStateAllowed.AdditionalMethods

}	//	End of namespace
